{{- if .Values.networkPolicies.enabled }}
{{- if or (not .Values.global.minio.enabled) (not .Values.postgresql.install) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-sidekiq
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: 
    matchLabels:
      app: sidekiq   # for database and objectStorage egress
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        # ONLY Block requests to AWS metadata IP
        except:
        - 169.254.169.254/32
{{- end }}
{{- end }}