{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-runner-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: 
    matchLabels:
      app: gitlab-runner-gitlab-runner   # runners need to access kube-api
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        # ONLY Block requests to AWS metadata IP
        except:
        - 169.254.169.254/32
{{- end }}