{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-webservice-runner
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: 
    matchLabels:
      app: gitlab-runner-gitlab-runner
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {} 
{{- end }}
